export const SERVICES = [
  {
    num: "01",
    icon: "Database",
    title: "CRM Setup and Optimization",
    tag: "GoHighLevel · HubSpot · Monday",
    desc: "Your CRM should be the brain of your business, remembering every lead, tracking every conversation, and triggering the right follow-up at the right time. Most CRMs sit unused because they were never set up right. We change that.",
    outcomes: [
      "Full CRM configuration and data migration",
      "Custom pipeline stages for your sales process",
      "Automated follow-up sequences and reminders",
      "Team training and onboarding documentation",
      "Ongoing optimization as your business grows",
    ],
  },
  {
    num: "02",
    icon: "GitMerge",
    title: "Workflow and Process Automation",
    tag: "Zapier · Make · Native APIs",
    desc: "Every manual handoff in your business is a failure point. Every tool that does not talk to another is wasted time. We connect your entire stack so information flows automatically, no more copy-pasting, no more cracks.",
    outcomes: [
      "Full tech stack audit and integration mapping",
      "Automated data flows between all your tools",
      "Client onboarding automation from inquiry to kickoff",
      "Internal task and notification workflows",
      "Error monitoring and system health checks",
    ],
  },
  {
    num: "03",
    icon: "Target",
    title: "Lead Generation Systems",
    tag: "Pipeline · Follow-Up · Nurture",
    desc: "A lead generation system that works while you sleep. We build the entire end-to-end pipeline from how a prospect first finds you to how they become a paying client, and automate every touchpoint.",
    outcomes: [
      "Lead capture forms, landing pages, and opt-ins",
      "Automated nurture sequences via email and SMS",
      "Lead scoring and qualification workflows",
      "Re-engagement campaigns for cold leads",
      "Performance tracking and conversion reporting",
    ],
  },
  {
    num: "04",
    icon: "TrendingUp",
    title: "Sales Funnel Design and Optimization",
    tag: "Funnels · Conversion · Revenue",
    desc: "Most businesses lose clients not because their offer is wrong but because the path to yes is unclear. We design and build funnels that guide your prospects from awareness to decision with confidence.",
    outcomes: [
      "Funnel strategy and customer journey mapping",
      "Landing page and sales page design",
      "Checkout and onboarding flow optimization",
      "A/B testing and conversion rate optimization",
      "Monthly funnel performance reviews",
    ],
  },
  {
    num: "05",
    icon: "Megaphone",
    title: "Social Media and Marketing Execution",
    tag: "Strategy · Content · Growth",
    desc: "Consistent marketing should not require you to live on your phone. We build your strategy, create your content calendar, and execute campaigns that generate predictable results.",
    outcomes: [
      "Social media strategy and content planning",
      "Content creation, scheduling, and publishing",
      "Email marketing campaigns and newsletters",
      "Paid ad strategy and campaign management",
      "Monthly analytics reporting and review",
    ],
  },
  {
    num: "06",
    icon: "CalendarCheck",
    title: "Appointment Booking Systems",
    tag: "Booking · Onboarding · Scheduling",
    desc: "Your time is your most valuable asset. Let clients book themselves, fill intake forms, make payments, and receive confirmation, all without a single back-and-forth. You just show up.",
    outcomes: [
      "Booking page design and calendar integration",
      "Automated confirmation and reminder sequences",
      "Pre-call intake forms and questionnaires",
      "Payment collection and invoice automation",
      "No-show and reschedule management workflows",
    ],
  },
]

export const TOOLS = [
  { name: "GoHighLevel",      logo: "/icons/tools/gohighlevel.svg",      iconOnly: true },
  { name: "HubSpot",          logo: "/icons/tools/hubspot.svg" },
  { name: "Monday.com",       logo: "/icons/tools/monday.svg" },
  { name: "Zapier",           logo: "/icons/tools/zapier.svg" },
  { name: "Make",             logo: "/icons/tools/make.svg" },
  { name: "ActiveCampaign",   logo: "/icons/tools/activecampaign.svg",   iconOnly: true },
  { name: "Calendly",         logo: "/icons/tools/calendly.svg" },
  { name: "Stripe",           logo: "/icons/tools/stripe.svg" },
  { name: "Mailchimp",        logo: "/icons/tools/mailchimp.svg" },
  { name: "Notion",           logo: "/icons/tools/notion.svg" },
  { name: "Slack",            logo: "/icons/tools/slack.svg" },
  { name: "Google",           logo: "/icons/tools/googleworkspace.svg" },
  { name: "Typeform",         logo: "/icons/tools/typeform.svg" },
  { name: "Airtable",         logo: "/icons/tools/airtable.svg" },
]

export const BOOKING_URL = "https://api.leadconnectorhq.com/widget/booking/IKqC5JSvzvRrK3N1qfJ1"
