export const SERVICES = [
  {
    num: "01",
    icon: "Database",
    title: "CRM Setup and Optimization",
    tag: "GoHighLevel · HubSpot · Monday",
    desc: "Your business should remember everything, even when you don't. Leads shouldn't disappear. Customers shouldn't be forgotten. Your CRM should become the central operating system of your business, automatically tracking conversations, follow-ups, deals, and customer relationships.",
    outcomes: [
      "Full CRM configuration and data migration",
      "Custom pipeline stages for your sales process",
      "Automated follow-up sequences and reminders",
      "Team training and onboarding documentation",
      "Ongoing optimization as your business grows",
    ],
  },
  {
    num: "02",
    icon: "GitMerge",
    title: "Workflow & Process Automation",
    tag: "Zapier · Make · Native APIs",
    desc: "Remove repetitive work. Keep the important work. Every manual task costs time. Every copy-and-paste creates room for mistakes. We connect your tools so information flows automatically from one system to another.",
    outcomes: [
      "Business process mapping and workflow design",
      "Zapier & Make automations and API integrations",
      "Client onboarding automation",
      "Internal notifications and approval workflows",
      "Error monitoring and automation documentation",
    ],
  },
  {
    num: "03",
    icon: "Target",
    title: "Lead Generation Systems",
    tag: "Pipeline · Follow-Up · Nurture",
    desc: "Build a pipeline that never stops working. Finding customers shouldn't depend on luck or posting every day. We build lead generation systems that attract, qualify, nurture, and convert prospects automatically.",
    outcomes: [
      "Lead capture forms, landing pages, and opt-ins",
      "Automated nurture sequences via email and SMS",
      "Lead scoring and qualification workflows",
      "Re-engagement campaigns for cold leads",
      "Performance tracking and conversion reporting",
    ],
  },
  {
    num: "04",
    icon: "TrendingUp",
    title: "Sales Funnel Design & Optimization",
    tag: "Funnels · Conversion · Revenue",
    desc: "Turn interest into revenue. A great offer deserves a buying journey that feels simple. We design funnels that remove friction, answer objections, and guide prospects confidently toward becoming paying clients.",
    outcomes: [
      "Funnel strategy and customer journey mapping",
      "Landing page and sales page design",
      "Checkout and onboarding flow optimization",
      "A/B testing and conversion rate optimization",
      "Monthly funnel performance reviews",
    ],
  },
  {
    num: "05",
    icon: "Megaphone",
    title: "Social Media & Marketing Execution",
    tag: "Strategy · Content · Growth",
    desc: "Stay visible without living on your phone. Marketing should build trust before the sales conversation begins. We create and execute marketing systems that consistently keep your business in front of the right audience.",
    outcomes: [
      "Content strategy and content calendar",
      "Graphic design and copywriting",
      "Social media management and paid advertising",
      "Email campaigns",
      "Performance reporting and continuous optimization",
    ],
  },
  {
    num: "06",
    icon: "CalendarCheck",
    title: "Appointment Booking Systems",
    tag: "Booking · Onboarding · Scheduling",
    desc: "Your time is your most valuable asset. Let clients book themselves, fill intake forms, make payments, and receive confirmation, all without a single back-and-forth. You just show up.",
    outcomes: [
      "Booking page design and calendar integration",
      "Automated confirmation and reminder sequences",
      "Pre-call intake forms and questionnaires",
      "Payment collection and invoice automation",
      "No-show and reschedule management workflows",
    ],
  },
]

export const TOOLS = [
  { name: "GoHighLevel",      logo: "/icons/tools/gohighlevel.svg",      iconOnly: true },
  { name: "HubSpot",          logo: "/icons/tools/hubspot.svg" },
  { name: "Monday.com",       logo: "/icons/tools/monday.svg",             iconOnly: true },
  { name: "Zapier",           logo: "/icons/tools/zapier.svg" },
  { name: "Make",             logo: "/icons/tools/make.svg" },
  { name: "ActiveCampaign",   logo: "/icons/tools/activecampaign.svg",   iconOnly: true },
  { name: "Calendly",         logo: "/icons/tools/calendly.svg" },
  { name: "Stripe",           logo: "/icons/tools/stripe.svg" },
  { name: "Mailchimp",        logo: "/icons/tools/mailchimp.svg" },
  { name: "Notion",           logo: "/icons/tools/notion.svg" },
  { name: "Slack",            logo: "/icons/tools/slack.svg" },
  { name: "Google",           logo: "/icons/tools/googleworkspace.svg" },
  { name: "Typeform",         logo: "/icons/tools/typeform.svg",           iconOnly: true },
  { name: "Airtable",         logo: "/icons/tools/airtable.svg" },
]

export const BOOKING_URL = "https://api.leadconnectorhq.com/widget/booking/IKqC5JSvzvRrK3N1qfJ1"
